insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(4,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=autop418;cat=autop089;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_auto_emergency-road-service',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20546,'dart_auto_emergency-road-service','auto:emergency-road-service','http://www.csaa.com/auto/emergency-road-service');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(5,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=autop418;cat=autop131;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_auto_buying-a-car',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20547,'dart_auto_buying-a-car','auto:buying-a-car','http://www.csaa.com/auto/buying-a-car');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(6,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=autop418;cat=autop916;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_auto_dmv-services',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20548,'dart_auto_dmv-services','auto:dmv-services','http://www.csaa.com/auto/dmv-services');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(7,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=autop418;cat=autop701;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_auto_mobile-navigation-solutions',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20549,'dart_auto_mobile-navigation-solutions','auto:mobile-navigation-solutions','http://www.csaa.com/auto/mobile-navigation-solutions');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(8,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=autop418;cat=autop750;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_auto_car-traffic-safety',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20550,'dart_auto_car-traffic-safety','auto:car-traffic-safety','http://www.csaa.com/auto/car-traffic-safety');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(9,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=autop418;cat=autop661;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_auto_car-repair',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20551,'dart_auto_car-repair','auto:car-repair','http://www.csaa.com/auto/car-repair');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(10,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=autop418;cat=autop013;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_auto_car-driving-commuting',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20552,'dart_auto_car-driving-commuting','auto:car-driving-commuting','http://www.csaa.com/auto/driving-commuting');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(11,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=autop418;cat=autop801;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_auto_selling-a-car',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20553,'dart_auto_selling-a-car','auto:selling-a-car','http://www.csaa.com/auto/selling-a-car');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(12,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=autop418;cat=autop326;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_auto_landing',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20554,'dart_auto_landing','auto:home','http://www.csaa.com/auto');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(13,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=joina538;cat=joina888;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_membership_join',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20555,'dart_membership_join','membership:join','https://www.csaa.com/membership/join');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(14,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=joina538;cat=joina161;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_membership_order_join',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20556,'dart_membership_order_join','membership:order:join','https://www.csaa.com/membership/order/join');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(15,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=joina538;cat=joina396;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_my-aaa-membership-payment-confirm',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20557,'dart_my-aaa-membership-payment-confirm','global-utilities:my-aaa-membership-payment-confirm','http://www.csaa.com/my-aaa/membership/payment-confirm');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(16,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=gener462;cat=csaah065;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_homepage',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20558,'dart_homepage','home','http://www.csaa.com');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(17,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=gener462;cat=hybri764;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_insurance_vehicle-insurance_hybrid-owners-save-on-aaa-auto-insurance',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20559,'dart_insurance_vehicle-insurance_hybrid-owners-save-on-aaa-auto-insurance','insurance:vehicle-insurance:hybrid-owners-save-on-aaa-auto-insurance','http://www.csaa.com/insurance/vehicle-insurance/hybrid-owners-save-on-aaa-auto-insurance');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(18,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=findu474;cat=findu190;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_about-aaa_find-us',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20560,'dart_about-aaa_find-us','about-aaa:find-us','http://www.csaa.com/about-aaa/find-us');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(19,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=insur611;cat=insur133;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_insurance-landing',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20561,'dart_insurance-landing','insurance:home','http://www.csaa.com/insurance');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(20,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=insur611;cat=insur021;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_insurance_vehicle-insurance',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20562,'dart_insurance_vehicle-insurance','insurance:vehicle-insurance','http://www.csaa.com/insurance/vehicle-insurance');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(21,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=insur611;cat=insur155;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_insurance_vehicle-insurance_motorcycle-insurance',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20563,'dart_insurance_vehicle-insurance_motorcycle-insurance','insurance:vehicle-insurance:motorcycle-insurance','http://www.csaa.com/insurance/vehicle-insurance/motorcycle-insurance');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(22,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=insur611;cat=insur083;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_insurance_vehicle-insurance_watercraft-insurance',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20564,'dart_insurance_vehicle-insurance_watercraft-insurance','insurance:vehicle-insurance:watercraft-insurance','http://www.csaa.com/insurance/vehicle-insurance/watercraft-insurance');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(23,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=insur611;cat=insur714;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_insurance_property-insurance',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20565,'dart_insurance_property-insurance','insurance:property-insurance','http://www.csaa.com/insurance/property-insurance');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(24,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=insur611;cat=insur480;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_insurance_property-insurance_renters-insurance',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20566,'dart_insurance_property-insurance_renters-insurance','insurance:property-insurance:renters-insurance','http://www.csaa.com/insurance/property-insurance/renters-insurance');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(25,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=insur611;cat=insur499;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_insurance_property-insurance_rental-property-insurance',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20567,'dart_insurance_property-insurance_rental-property-insurance','insurance:property-insurance:rental-property-insurance','http://www.csaa.com/insurance/property-insurance/rental-property-insurance');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(26,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=insur611;cat=insur901;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_insurance_property-insurance_flood-insurance',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20568,'dart_insurance_property-insurance_flood-insurance','insurance:property-insurance:flood-insurance','http://www.csaa.com/insurance/property-insurance/flood-insurance');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(27,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=insur611;cat=insur162;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_insurance_property-insurance_umbrella-insurance',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20569,'dart_insurance_property-insurance_umbrella-insurance','insurance:property-insurance:umbrella-insurance','http://www.csaa.com/insurance/property-insurance/umbrella-insurance');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(28,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=insur611;cat=insur484;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_insurance_life-insurance-and-annuities',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20570,'dart_insurance_life-insurance-and-annuities','insurance:life-insurance-and-annuities','http://www.csaa.com/insurance/life-insurance-and-annuities');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(29,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=insur611;cat=insur319;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_insurance_file-a-claim_file-claim',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20571,'dart_insurance_file-a-claim_file-claim','insurance:file-a-claim:file-claim','http://www.csaa.com/insurance/file-a-claim/file-claim');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(30,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=trave361;cat=trave585;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_travel',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20572,'dart_travel','travel:home','http://www.csaa.com/travel');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(31,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=disco781;cat=disco644;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_discounts',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20573,'dart_discounts','discounts:home','http://www.csaa.com/discounts');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(32,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=finan334;cat=finan954;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_membership_view-aaa-benefits/aaa-rewards-easy-to-earn-easy-to-use',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20574,'dart_membership_view-aaa-benefits/aaa-rewards-easy-to-earn-easy-to-use','membership:view-aaa-benefits:aaa-rewards-easy-to-earn-to-use','http://www.csaa.com/membership/view-aaa-benefits/aaa-rewards-easy-to-earn-easy-to-use');
insert into aaa_tag_tags_stg(tag_id, tag_script,tag_type, tag_name, agency_id) values(33,'var axel=Math.random();var a=axel*10000000000000;var iframe=document.createElement("iframe");iframe.src="http://fls.doubleclick.net/activityi;src=2331885;type=finan334;cat=finan747;ord="+a+"?";iframe.width=1;iframe.height=1;iframe.borderframe=0;document.body.append(iframe);','iframe','dart_travel_research-planning_secure-your-funds-while-travelling',6);
insert into aaa_tag_dart_url_stg(page_id,tag_name,page_name,page_url) values(20575,'dart_travel_research-planning_secure-your-funds-while-travelling','travel:research-planning:secure-your-funds-while-travelling','http://www.csaa.com/travel/research-planning/secure-your-funds-while-traveling');
