update aaa_tag_pages set page_url = 'csaa.com' where page_ID = 20558;
update aaa_tag_pages set page_url = 'csaa.com/about-aaa/find-us' where page_ID = 20560;
update aaa_tag_pages set page_url = 'csaa.com/auto ' where page_ID = 20554;
update aaa_tag_pages set page_url = 'csaa.com/auto/buying-a-car' where page_ID = 20547;
update aaa_tag_pages set page_url = 'csaa.com/auto/car-repair' where page_ID = 20551;
update aaa_tag_pages set page_url = 'csaa.com/auto/car-traffic-safety' where page_ID = 20550;
update aaa_tag_pages set page_url = 'csaa.com/auto/dmv-services' where page_ID = 20548;
update aaa_tag_pages set page_url = 'csaa.com/auto/driving-commuting ' where page_ID = 20552;
update aaa_tag_pages set page_url = 'csaa.com/auto/emergency-road-service' where page_ID = 20546;
update aaa_tag_pages set page_url = 'csaa.com/auto/mobile-navigation-solutions ' where page_ID = 20549;
update aaa_tag_pages set page_url = 'csaa.com/auto/selling-a-car ' where page_ID = 20553;
update aaa_tag_pages set page_url = 'csaa.com/discounts' where page_ID = 20573;
update aaa_tag_pages set page_url = 'csaa.com/insurance' where page_ID = 20561;
update aaa_tag_pages set page_url = 'csaa.com/insurance/file-a-claim/file-claim' where page_ID = 20571;
update aaa_tag_pages set page_url = 'csaa.com/insurance/life-insurance-and-annuities ' where page_ID = 20570;
update aaa_tag_pages set page_url = 'csaa.com/insurance/property-insurance ' where page_ID = 20565;
update aaa_tag_pages set page_url = 'csaa.com/insurance/property-insurance/flood-insurance ' where page_ID = 20568;
update aaa_tag_pages set page_url = 'csaa.com/insurance/property-insurance/rental-property-insurance ' where page_ID = 20567;
update aaa_tag_pages set page_url = 'csaa.com/insurance/property-insurance/renters-insurance ' where page_ID = 20566;
update aaa_tag_pages set page_url = 'csaa.com/insurance/property-insurance/umbrella-insurance' where page_ID = 20569;
update aaa_tag_pages set page_url = 'csaa.com/insurance/vehicle-insurance' where page_ID = 20562;
update aaa_tag_pages set page_url = 'csaa.com/insurance/vehicle-insurance/hybrid-owners-save-on-aaa-auto-insurance ' where page_ID = 20559;
update aaa_tag_pages set page_url = 'csaa.com/insurance/vehicle-insurance/motorcycle-insurance ' where page_ID = 20563;
update aaa_tag_pages set page_url = 'csaa.com/insurance/vehicle-insurance/watercraft-insurance ' where page_ID = 20564;
update aaa_tag_pages set page_url = 'csaa.com/membership/view-aaa-benefits/aaa-rewards-easy-to-earn-easy-to-use' where page_ID = 20574;
update aaa_tag_pages set page_url = 'csaa.com/my-aaa/membership/payment-confirm' where page_ID = 20557;
update aaa_tag_pages set page_url = 'csaa.com/travel ' where page_ID = 20572;
update aaa_tag_pages set page_url = 'csaa.com/travel/research-planning/secure-your-funds-while-traveling ' where page_ID = 20575;
update aaa_tag_pages set page_url = 'csaa.com/membership/join ' where page_ID = 20555;
update aaa_tag_pages set page_url = 'csaa.com/membership/order/join ' where page_ID = 20556;
